### ISSUE TITLE
Integrating with geofencing

### ISSUE THREAD

**Issue by LwsBtlr** [nfarina/homebridge-kevo#3]
I have my kevo plus setup with homebridge, but I wuld like to setup a rule via IFTTT (or similar) that triggered "when this devices leave home, lock the door" but I haven't figured out how to do it.

**Comment by Tiger519** [comment]
Not sure if you are even still using this, but you would need to do this via Homekit (the Apple Home app or similar 3rd party app). There have been a lot of improvements to Homekit and geofencing since 2016, so you should definitely be able to accomplish this now.

If you are wanting to use this with Homebridge but not Homekit (i.e. control from another platform such as IFTTT only), that is not possible with this plugin. I have seen some other libraries out there using similar functionality to access the Kevo functionality without being tied to Homekit, but that would not be covered within this plugin.
